//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class academic
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string specialization { get; set; }
        public Nullable<int> title_assignment { get; set; }
    }
}
