//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class гимназист
    {
        public int id { get; set; }
        public string фамилия { get; set; }
        public string предмет { get; set; }
        public string школа { get; set; }
        public Nullable<double> баллы { get; set; }
    }
}
