//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up_wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class direction_director
    {
        public int employee_id { get; set; }
        public Nullable<int> experience { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
