//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up_wpf.Model
{
    using System;
    using System.Collections.Generic;

    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.employee1 = new HashSet<employee>();
        }

        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> chief { get; set; }


        public virtual department department { get; set; }
        public virtual direction_director direction_director { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual engineer engineer { get; set; }
        public virtual teacher teacher { get; set; }

    }
}
