//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up_wpf.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPEntities : DbContext
    {
        public UPEntities()
            : base("name=UPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academic> academic { get; set; }
        public virtual DbSet<animal> animal { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<direction_director> direction_director { get; set; }
        public virtual DbSet<discipline> discipline { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<engineer> engineer { get; set; }
        public virtual DbSet<exam> exam { get; set; }
        public virtual DbSet<faculty> faculty { get; set; }
        public virtual DbSet<flower> flower { get; set; }
        public virtual DbSet<management> management { get; set; }
        public virtual DbSet<speciality> speciality { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<ученики> ученики { get; set; }
        public virtual DbSet<гимназист> гимназист { get; set; }
    }
}
